version: '3.8'

services:
  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: battle-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - battle-network

  # Battle API Server
  battle-api:
    build:
      context: ./packages/battle-api
      dockerfile: Dockerfile
    container_name: battle-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this
      - CORS_ORIGIN=http://localhost:3000
      - BATTLE_TURN_TIMEOUT=30
      - MAX_PLAYERS_PER_BATTLE=2
      - TOKEN_EXPIRY_PARTICIPANT=1h
      - TOKEN_EXPIRY_SPECTATOR=24h
    depends_on:
      - redis
    volumes:
      - ./packages/battle-api/src:/app/src
      - /app/node_modules
    networks:
      - battle-network

  # Battle Web Client
  battle-web:
    build:
      context: ./packages/battle-web
      dockerfile: Dockerfile
    container_name: battle-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - REACT_APP_SOCKET_URL=http://localhost:3001
      - GENERATE_SOURCEMAP=false
    depends_on:
      - battle-api
    volumes:
      - ./packages/battle-web/src:/app/src
      - ./packages/battle-web/public:/app/public
      - /app/node_modules
    networks:
      - battle-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: battle-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - battle-api
      - battle-web
    networks:
      - battle-network
    profiles:
      - production

volumes:
  redis_data:

networks:
  battle-network:
    driver: bridge